### PR TITLE
Phase

### PR DESCRIPTION
**Pull request by jxnxsdev**

### CODE REVIEW

**Comment by ComputerElite** [comment]
@phaze-the-dumb are you ok with the name like jonas spelled it?

**Comment by ComputerElite** [comment]
Also fix you merge conflicts duh

**Comment by phaze-the-dumb** [comment]
> @phaze-the-dumb are you ok with the name like jonas spelled it?

sure

**Comment by jxnxsdev** [comment]
If Phase can call me John, i'm calling him Phase

**Comment by ComputerElite** [comment]
Well you didn't say no to John

**Comment by phaze-the-dumb** [comment]
john. merge fix your conflicts

**Comment by phaze-the-dumb** [comment]
how did you even manage to fuck that up lmfao

**Comment by ComputerElite** [comment]
phaz, learn grammar

**Comment by phaze-the-dumb** [comment]
LMFAO i didn't even realise i did that xD

**Comment by jxnxsdev** [comment]
> LMFAO i didn't even realise i did that xD

Me when Scotloader2

**Comment by phaze-the-dumb** [comment]
loadscotter2

**Comment by jxnxsdev** [comment]
Schrottland3

**Comment by ComputerElite** [comment]
SCOTLAND FOREEVER

**Comment by phaze-the-dumb** [comment]
SCROTLAND!!!!!

**Comment by jxnxsdev** [comment]
SCHOTTLAND FÜR IMMER

**Pull request merged**
