### PR TITLE
Face

### PR DESCRIPTION
**Pull request by jxnxsdev**
https://discord.com/channels/983033385721151538/1067187672986165398/1207101139070353418

### CODE REVIEW

**Comment by phaze-the-dumb** [comment]
why are you so boring

**Comment by jxnxsdev** [comment]
Idk probably a bug in my code

**Comment by phaze-the-dumb** [comment]
close this pr please, it is not the family friendly content we want on oculusdb thank you goodbye

**Comment by jxnxsdev** [comment]
Ok Face

**Comment by phaze-the-dumb** [comment]
wait you actually closed it???
what is it with people actually listening to me today????

**Comment by jxnxsdev** [comment]
Oh I forgot.

**Comment by phaze-the-dumb** [comment]
thats about what i expected

**Comment by ComputerElite** [comment]
What the heck, the quotes are getting more wild

**Comment by jxnxsdev** [comment]
It was just to good to not quote

**Pull request merged**
