### PR TITLE
add more query parameters so you can select your oculusdb experience

### PR DESCRIPTION
**Pull request by phaze-the-dumb**

### CODE REVIEW

**Comment by ComputerElite** [comment]
wanna work on finishing the details page now? thank

**Comment by phaze-the-dumb** [comment]
never!

**Comment by jxnxsdev** [comment]
The site isnt gay enough

**Comment by phaze-the-dumb** [comment]
How can i make it gayer?

apart from putting men kissing each other on it, i'm not doing that.

**Comment by jxnxsdev** [comment]
hmm

**Comment by jxnxsdev** [comment]
You know the dvd logo? Make it so that it appears in a 1/100 change but it's a pride flag

**Comment by ComputerElite** [comment]
hey I got code for that https://computerelite.github.io/fun/BouncingLogo.html

**Comment by jxnxsdev** [comment]
Can you make it hit the corner after the 5th bounce?

**Comment by ComputerElite** [comment]
Oh also, add a remove pride flag option which tells you to fuck off

**Comment by ComputerElite** [comment]
_add a settings page first tho_

**Comment by jxnxsdev** [comment]
And an option to "ungay the site" which saves a boolean in the local storage which always redirects you to a rickroll when loading the page

**Comment by ComputerElite** [comment]
~~and a small pop up in the bottom left corner which makes you aware of it's existences~~

**Comment by jxnxsdev** [comment]
"Free Collar" button

**Comment by phaze-the-dumb** [comment]
> Oh also, add a remove pride flag option which tells you to fuck off

https://cdn.phaz.uk/i/firefox_dMnBVCT6fC.mp4 like this?

**Comment by ComputerElite** [comment]
amaaazing

**Comment by ComputerElite** [comment]
yes

**Comment by jxnxsdev** [comment]
why do you have the js fuck docs open

**Comment by phaze-the-dumb** [comment]
> why do you have the js fuck docs open

shoosh

**Comment by phaze-the-dumb** [comment]
https://cdn.phaz.uk/i/firefox_QiuBRPpMVe.mp4 more gay?

**Comment by jxnxsdev** [comment]
Hmm, looks good, but maybe make the angle a bit bigger

**Comment by phaze-the-dumb** [comment]
its random

**Pull request merged**
