### PR TITLE
i just wanted to add one quote.......

### PR DESCRIPTION
**Pull request by phaze-the-dumb**

### CODE REVIEW

**Comment by phaze-the-dumb** [comment]
fuck me

**Comment by phaze-the-dumb** [comment]
how did you break it this much

**Comment by ComputerElite** [comment]
yes

**Comment by phaze-the-dumb** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by ComputerElite** [comment]
Thanks for bringing back the commits I deleted

**Pull request merged**
