### PR TITLE
more quotes...

### PR DESCRIPTION
**Pull request by phaze-the-dumb**

### CODE REVIEW

**Comment by phaze-the-dumb** [comment]
i feel like this could go downhill very quickly

**Comment by ComputerElite** [comment]
it indeed can

**Comment by ComputerElite** [comment]
I feel like before we go live we should remove the weird ones

**Comment by ComputerElite** [comment]
but they're fun to read

**Comment by ComputerElite** [comment]
Also, when did I say "Am I even legal?" lmfao

**Comment by ComputerElite** [comment]
phaze. Stop misquoting

**Comment by phaze-the-dumb** [comment]
you said it!

**Comment by ComputerElite** [comment]
at least add [...}

**Comment by phaze-the-dumb** [comment]
just because i didn't quote the whole thing doesn't mean that its misquoting...

**Comment by jxnxsdev** [comment]
Can we have the one where you said to me "You will never make the Popup good enough. Users are too stupid"?

**Comment by ComputerElite** [comment]
that makes it worse, doesn't it lmao

**Comment by ComputerElite** [comment]
> Can we have the one where you said to me "You will never make the Popup good enough. Users are too stupid"?

Yeah, ask phaz politely

**Comment by jxnxsdev** [comment]
Phaze please UwU

**Comment by phaze-the-dumb** [comment]
what do i get out of it?

**Comment by ComputerElite** [comment]
yeah please mr furry

**Comment by jxnxsdev** [comment]
> what do i get out of it?

I wont throw you around for the next month

**Comment by phaze-the-dumb** [comment]
hmm pretty good deal... was it computer that said it to you?

**Comment by ComputerElite** [comment]
I think so

**Comment by ComputerElite** [comment]
John lmfao

**Comment by ComputerElite** [comment]
and you made the other quote even worse. Amazing work

**Comment by phaze-the-dumb** [comment]
> and you made the other quote even worse. Amazing work

but its quoted more accurately...

**Comment by jxnxsdev** [comment]
I'm John now ig

**Comment by phaze-the-dumb** [comment]
> John lmfao

oh wait lmfao

**Comment by ComputerElite** [comment]
image

**Comment by ComputerElite** [comment]
@hdgamer1404Jonas do you approve of your name how phaz spelled it?

**Comment by jxnxsdev** [comment]
I think phaze should add quotes to the header next

**Comment by phaze-the-dumb** [comment]
i'll add quotes everywhere, everything shall be a quote.

**Comment by jxnxsdev** [comment]
> @hdgamer1404Jonas do you approve of your name how phaz spelled it?

I'm not John and i'm not wet. Thats all i gotta say

**Comment by ComputerElite** [comment]
> i'll add quotes everywhere, everything shall be a quote.

Add that as a quote

**Comment by ComputerElite** [comment]
> > @hdgamer1404Jonas do you approve of your name how phaz spelled it?
> 
> I'm not John and i'm not wet. Thats all i gotta say

💀

**Comment by jxnxsdev** [comment]
> > i'll add quotes everywhere, everything shall be a quote.
> 
> Add that as a quote

Just Add the whole discussion as a quote

**Comment by phaze-the-dumb** [comment]
why finish the ui when i can add more quotes?

**Comment by ComputerElite** [comment]
because the current backend is shit

**Comment by phaze-the-dumb** [comment]
maybe we should write the backend in rust

then it will be the best.

**Comment by ComputerElite** [comment]
and I wanna move everything over to the rewrite including the nodes.

**Comment by ComputerElite** [comment]
I'm not rewriting the backend. It works already

**Comment by jxnxsdev** [comment]
> maybe we should write the backend in rust
> 
> then it will be the best.

Shakespear language

**Comment by ComputerElite** [comment]
Oh god you're making the quote worse and worse with every commit qwq. And all that while keeping it accurate

**Comment by phaze-the-dumb** [comment]
go fuck yourself john

**Comment by phaze-the-dumb** [comment]
you're getting dropped back down to john now

**Comment by jxnxsdev** [comment]
Screw you phaze

**Comment by phaze-the-dumb** [comment]
> Oh god you're making the quote worse and worse with every commit qwq. And all that while keeping it accurate

¯\\\_(ツ)\_/¯

**Comment by jxnxsdev** [comment]
I'll fork this repo

**Comment by ComputerElite** [comment]
you forgot to escape the backslash

**Comment by jxnxsdev** [comment]
Certified phaze moment *proceeds to fuck up the buttons*

**Comment by phaze-the-dumb** [comment]
> you forgot to escape the backslash

shutteth the fuck up

**Comment by ComputerElite** [comment]
"proceeds to fuck..." - John

**Comment by phaze-the-dumb** [comment]
WHAT

**Comment by phaze-the-dumb** [comment]
oh yeh

**Comment by phaze-the-dumb** [comment]
JOHN! UNFORK THIS REPO RIGHT FUCKING NOW

**Comment by jxnxsdev** [comment]
I did...

... only because i only forked the main branch

**Comment by ComputerElite** [comment]
HAH

**Comment by ComputerElite** [comment]
GET FUCKED

**Comment by phaze-the-dumb** [comment]
hah

**Comment by phaze-the-dumb** [comment]
i think he is getting fucked.

**Comment by jxnxsdev** [comment]
nah

**Pull request merged**
