### PR TITLE
something?

### PR DESCRIPTION
**Pull request by phaze-the-dumb**

### CODE REVIEW

**Comment by ComputerElite** [comment]
Phaz...
"ComputerElite according to Jonas" if anything

**Comment by ComputerElite** [comment]
As said before quotes like that are on the edge.

**Comment by ComputerElite** [comment]
pun intended

**Comment by phaze-the-dumb** [comment]
:)

**Comment by ComputerElite** [comment]
I'm fine with that one

**Comment by ComputerElite** [comment]
the other one gotta be changed

**Comment by ComputerElite** [comment]
well, the source at least

**Comment by ComputerElite** [comment]
"He didn't want to come. Well, come, not cum. You know what I mean duh." - ComputerElite

or that if you want

**Comment by phaze-the-dumb** [comment]
"He didn't want to come" did you or did you not say that

**Comment by ComputerElite** [comment]
I said that

**Comment by ComputerElite** [comment]
but as said yesterday: The receiver of the message decides on the meaning. Not the sender

**Comment by ComputerElite** [comment]
"He didn't want to cum. Well, come, not cum. You know what I mean duh." - ComputerElite

btw meant to send that

**Comment by ComputerElite** [comment]
Also, can we like improve the random function?

**Comment by phaze-the-dumb** [comment]
uhhh
i can hook into the crypto function... but i feel thats thats a bit ott for a quote system. i'll have a look, don't merge yet...

**Comment by ComputerElite** [comment]
thanks

**Comment by ComputerElite** [comment]
or perhaps multiply the js random function with the current time or something like that?

**Comment by ComputerElite** [comment]
I think the open time of the page is more random than the random function lmao

**Comment by phaze-the-dumb** [comment]
nah i'll just log like the last 5 quotes and not use any of those

**Comment by ComputerElite** [comment]
huh

**Comment by jxnxsdev** [comment]
> Phaz... "ComputerElite according to Jonas" if anything

Me?

**Comment by ComputerElite** [comment]
Am I misremembering? could be

**Comment by phaze-the-dumb** [comment]
it was

**Comment by jxnxsdev** [comment]
What Quote are we talking about? The collar one?

**Comment by ComputerElite** [comment]
doesn't matter, you're not as source

**Comment by ComputerElite** [comment]
first commit

**Comment by jxnxsdev** [comment]
idk i just read my name

**Comment by ComputerElite** [comment]
ah

**Comment by ComputerElite** [comment]
hm, why not make it like 40% of the quotes list length. Just so you see more

**Comment by ComputerElite** [comment]
actually nvm. Let some quotes be a surprise

**Comment by ComputerElite** [comment]
Yeah that's way better

**Comment by ComputerElite** [comment]
thanks phaze

**Pull request merged**
