### PR TITLE
oculdu

### PR DESCRIPTION
**Pull request by phaze-the-dumb**
- Fix price container header going opaque during animation
- Love you computer :3
- Supported language filters
- Fix rendering bug with non-app results

### CODE REVIEW

**Comment by ComputerElite** [comment]
Mind if we put language filtering into the backend. We had a conversation about filtering in frontend before

**Comment by phaze-the-dumb** [comment]
Yeh sure i don't mind changing it

**Comment by ComputerElite** [comment]
supportedInAppLanguages query string has been added to search api. it's case sensitive rn. Seperate languages by comma

**Comment by ComputerElite** [comment]
:(

**Comment by phaze-the-dumb** [comment]
wait i had an open pr?

**Comment by phaze-the-dumb** [comment]
i was trying to pr something and it wouldn't merge lmfao

**Pull request closed without merging**
